### ISSUE TITLE
Pretty Picture

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Curtin-Motorsport-Team/PDM-2017#1]
If you send me a picture of the PDM board so far we can add it to the project's front page. Reckon it's worth it?

**Comment by timothymoisley** [comment]
Hey,

Sorry its a bit late (didn’t actually finish the altium files) until today

**Comment by Michael-F-Bryan** [comment]
Want to drop a screenshot in this issue so I can add it to your front page like I did with Tom's [CarLogs] repo?

[CarLogs]: https://github.com/Curtin-Motorsport-Team/CarLogs

**Comment by timothymoisley** [comment]
![pdm mk21 3d 1 1](https://cloud.githubusercontent.com/assets/22444801/26195993/17d22360-3bf0-11e7-8511-d4a88f5ebca7.JPG)
